apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-09-18T03:01:51Z
  labels:
    app: shopify-internship
  name: shopify-internship-deployment
  namespace: default
  resourceVersion: "52897"
  selfLink: /api/v1/namespaces/default/services/shopify-internship-deployment
  uid: 30fcb974-baef-11e8-aa60-42010a960078
spec:
  clusterIP: 10.35.244.140
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30480
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: shopify-internship
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.221.22.137